server:
  port: 8081

spring:
  application:
    name: pringboot-security-lhy
  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: akdptmzbdpf10299!!

mybatis:
  mapper-locations: classpath:mappers/*.xml

jwt:
  issuer: test@naver.com
  secret_key: qqsTf/MIE9HSGVwB2vKaDtC7hI3RLOYPUSs4okbySBsm8eJH/YufLAP5oa5t7tghQZ3cjNOhZmd/zpwEpvwbuw==